services:
  valkey:
    image: docker.io/bitnami/valkey:8.1
    environment:
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD}
      VALKEY_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
    ports:
      - '6378:6379'
    volumes:
      - valkey_data:/bitnami/valkey/data

  telize:
    build: .
    ports:
      - '8080:8080'

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '6544:5432'
    environment:
      POSTGRES_DB: wpush
      POSTGRES_USER: wpush
      POSTGRES_PASSWORD: wpush

volumes:
  valkey_data:
    driver: local

  postgres_data:
    driver: local
